client: 
 serviceUrl: 
  default: http://localhost:8761/eureka
sqlStatement: SELECT * FROM message
sqlUrl: jdbc:h2:mem://testdb
sqlUser: root
sqlPassword: password
kafka.bootstrap-servers: localhost:9092 
kafka.requestReplyTopic: requestReply
kafka.group: group-id 
spring: 
 flyway: 
   enabled: true
   url: jdbc:h2:mem://testdb;DB_CLOSE_DELAY=-1
   locations: classpath:db/migration
   user: root
   password: password 
  jpa: 
    hibernate: 
      ddl-auto: none
