client: 
 serviceUrl: 
  default: http://localhost:8761/eureka
h2: 
 console: 
  enabled: true
spring:   
 datasource: 
  url: jdbc:h2:mem:DATABASE
  driver-class-name: org.h2.Driver
 jpa:
  database-platform: org.hibernate.dialect.H2Dialect
 flyway: 
  url: jdbc:h2:mem:DATABASE
  schemas: app-db 
  user: user
  password: password
  locations: classpath:db/migration
