spring:
 flyway:
   enabled: true
   locations: classpath:db\migration
   schemas: [jbt_db] 
 datasource:
   url: jdbc:h2:mem:~\DATABASE
   username: root
   password: password   
 h2:
  console:
   enabled: true